DaniBlogBundle_home:
    path:     /
    defaults: { _controller: DaniBlogBundle:Page:index }
    requirements:
        _method:  GET


DaniBlogBundle_contact:
    path:     /contact
    defaults: { _controller: DaniBlogBundle:Page:contact }
    requirements:
        _method:  GET


DaniBlogBundle_blog_show:
    pattern:  /{id}
    defaults: { _controller: DaniBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+


DaniBlogBundle_loggin:
    pattern:  /loggin
    defaults: { _controller: DaniBlogBundle:Page:loggin }
    requirements:
        _method:  GET