DaniBlogBundle_home:
    path:     /
    defaults: { _controller: DaniBlogBundle:Page:index }
    requirements:
        _method:  GET

DaniBlogBundle_contact:
    path:     /contact
    defaults: { _controller: DaniBlogBundle:Page:contact }
    requirements:
        _method:  GET